# Keyword setup
KEYWORDS = {
    "expression": {
        "primitives": ["regulates_expression", "regulates_translation"],
        "keywords": [
            "gene expression",
            "transcription",
            "RNA-seq",
            "DEG",
            "regulate",
            "regulation",
            "repress",
            "repression",
            "transcriptomic response",
            "activate",
            "activation",
            "induce",
            "induction",
            "stimulate",
            "enhance",
            "upregulate",
            "downregulate",
            "gene signature",
            "differential expression",
        ],
    },
    "PTM": {
        "primitives": ["post_translational_modification", "degrades_or_stabilises"],
        "keywords": [
            "post-translation",
            "PTM",
            "phosphorylation",
            "translation",
            "acetylation",
            "methylation",
            "ubiquitination",
            "SUMOylation",
            "glycosylation",
            "cleavage",
            "proteolysis",
            "proteasome",
            "chaperone",
            "protein degradation",
            "protein stability",
            "mutation",
            "protein abundance",
            "compartimentalize",
            "sequester",
            "shed",
        ],
    },
    "binding": {
        "primitives": ["binds_to", "modulates_molecule_activity", "converts_substrate"],
        "keywords": [
            "bind",
            "binding",
            "affinity",
            "interact",
            "ligand binding",
            "interaction",
            "Kd",
            "Ki",
            "IC50",
            "EC50",
            "occupancy",
            "docking",
            "allosteric",
            "competitive",
            "inhibitor",
            "activator",
            "modulator",
            "agonist",
            "antagonist",
            "enzyme activity",
            "catalytic activity",
            "substrate",
            "product",
        ],
    },
    "complex": {
        "primitives": ["modulates_complex", "localises_to"],
        "keywords": [
            "protein complex",
            "complex assembly",
            "complex disassembly",
            "dimerization",
            "oligomerization",
            "multimer",
            "subunit composition",
            "co-immunoprecipitation",
            "co-complex",
            "translocation",
            "cytoplasmic retention",
            "membrane trafficking",
            "vesicle transport",
            "endocytosis",
            "exocytosis",
            "secretion",
            "uptake",
            "localization",
            "relocation",
            "compartmentalization",
        ],
    },
    "pathways": {
        "primitives": ["modulates_pathway_activity", "chromatin_modification"],
        "keywords": [
            "pathway activation",
            "pathway inhibition",
            "signaling cascade",
            "signal transduction",
            "enrichment",
            "gene set",
            "pathway score",
            "upstream regulator",
            "network rewiring",
            "chromatin modification",
            "histone modification",
            "epigenetic regulation",
            "DNA methylation",
            "open chromatin",
            "closed chromatin",
            "acetylation",
            "transcriptional silencing",
            "repressive marks",
        ],
    },
    "functional": {
        "primitives": ["gain_of_function", "loss_of_function"],
        "keywords": [
            "gain-of-function",
            "loss-of-function",
            "GoF",
            "LoF",
            "mutation",
            "knockout",
            "knock-in",
            "knockdown",
            "gene silencing",
            "gene deletion",
            "CRISPR",
            "Cas9",
            "genetic perturbation",
            "missense",
            "nonsense",
            "frameshift",
            "truncation",
        ],
    },
    "phenotype": {
        "primitives": ["induces_phenotype", "alleviates_phenotype"],
        "keywords": [
            "phenotype",
            "cell state",
            "morphology",
            "differentiation",
            "senescence",
            "apoptosis",
            "proliferation",
            "arrest",
            "cell cycle",
            "migration",
            "adhesion",
            "fibrosis",
            "hypertrophy",
            "atrophy",
            "toxicity",
            "cell death",
            "viability",
            "survival",
            "rescue",
            "reversal",
            "recovery",
            "alleviation",
            "alleviate",
            "worsen",
            "enhance",
            "ameliorate",
            "disease",
            "functional consequence",
            "therapeutic effect",
        ],
    },
    "similarity": {
        "primitives": ["similar_to", "correlates_with", "participates_in"],
        "keywords": [
            "correlate",
            "associated with",
            "co-express",
            "co-regulate",
            "shared signature",
            "similar",
            "redundant",
            "related",
            "GO term",
            "biological process",
            "molecular function",
            "pathway membership",
            "similarity",
            "neighbor",
            "clustering",
            "co-occurrence",
            "co-mention",
            "enrichment",
            "embedding proximity",
        ],
    },
    "context": {
        "primitives": ["set_context"],
        "keywords": [
            "cell line",
            "cell type",
            "genetic background",
            "disease model",
            "treatment",
            "perturbation",
            "experimental context",
            "pre-treatment",
            "culture condition",
            "organism",
            "tissue",
            "developmental stage",
        ],
    },
}


MAP_TO_KEYWORDS = {
    "chemical": [
        "binding",
        "expression",
        "phenotype",
        "pathways",
    ],
    "gene": [
        "functional",
        "expression",
        "phenotype",
        "pathways",
    ],
    "context": [
        "pathways",
        "context",
        "expression",
        "phenotype",
        "similarity",
    ],
    "full": ["binding", "functional", "expression", "phenotype", "pathways", "context", "PTM", "similarity", "complex"],
}

# Tenacity setup
MAX_RETRIES = 2
BASE_DELAY = 1
MAX_DELAY = 3
